### ISSUE TITLE
Package Dependencies

### ISSUE THREAD

**Issue by ducduy20** [paescebu/CustomKeyboardKit#1]
There is a problem when I add to the project with package Dependencies

**Comment by paescebu** [comment]
@ducduy20 Hey! Thanks for trying out my Swift Package. Can you elaborate how the "problem" manifests ? :) 
Do you have an ssh key properly setup in your Xcode instance?
(I'm anyway thinking of switching to HTTPS for this particular package as i open sourced it)

**Comment by paescebu** [comment]
@ducduy20  i changed the SwiftUI-Introspect to use HTTPS for fetching the dependency. That should remove the requirement to setup anything special in Xcode (like SSH keys).

Did this solve the issue for you?

**Comment by paescebu** [comment]
Due to inactivity, i am closing this issue and mark it as resolved.
