### ISSUE TITLE
SwiftUI: Conditionally switch between custom / system keyboard

### ISSUE THREAD

**Issue by laosb** [paescebu/CustomKeyboardKit#11]
In our case the design calls for a text field with optional custom options (in custom keyboard), with a switch keyboard button in accessory view.

**Comment by paescebu** [comment]
@laosb 
Thanks for trying out my swift package! Do you have some example code that I could take a look at to try to find a solution?

**Comment by paescebu** [comment]
Hey @laosb,

I have here two examples that might help you.
- One is building a Keyboard that allows switching between two custom keyboards
- A second one is the possibility of switching between a native and a custom keyboard

I might search for something that allows a simpler approach out of the box from CustomKeyboardKit. 
Let me know if it helped!
[Approaches.zip](https://github.com/paescebu/CustomKeyboardKit/files/13257595/Approaches.zip)

**Comment by laosb** [comment]
Hi, sorry for the delay, but we ended up manually introspecting our way to attach a custom keyboard, and when switching just change the `inputView` property and reload input views.

That works well, so this approach may work in this package. It should be easy to accept a `Binding<Bool>` in the modifier, and/or more flexible `Binding<some Hashable?>` for switching between multiple custom keyboards & system.

**Comment by paescebu** [comment]
Hi @laosb
Thank you so much for your reply and suggestion.
If you feel that approach could benefit others, feel free to issue a PR that I can dice into.

It definitely sounds interesting. I will observe if that request to dynamically switch between Keyboards is something the Community would need.

Kind regards and all the best!
Pascal
