### ISSUE TITLE
SwiftUI GeometryReader not Working with .customKeyboard

### ISSUE THREAD

**Issue by l3rosiah** [paescebu/CustomKeyboardKit#13]
I've attempted to use a GeometryReader for a little bit more fine-tuned control over the keyboard and have not had any success. I tried outside and inside of the .customKeyboard modifier within a view, and both screw it up as to be completely unrecognizable.

**Comment by paescebu** [comment]
Hey @l3rosiah!
Thanks for trying my little library. 
Do you have some example code that I can take a look into?

I am not sure what I would expect using a GeometryReader inside the CustomKeyboard View. Have you tried limiting it's frame, like:
```swift
GeometryReader { proxy in
     ....
}
.frame(height: 200, width: 300) //or something along those lines
```

**Comment by l3rosiah** [comment]
Hi @paescebu, thank you so much for the quick response! My goal was to get a 75/25 or 66/34 split with two side-by-side views and I tried a couple different variations of something like below- even with just two rectangles they are squished down and the keyboard popup view is very short. I apologize if I am making a simple error as I am still relatively new to iOS development. I am running the latest versions of software and testing on an iPad.

`
import SwiftUI
import CustomKeyboardKit

extension CustomKeyboard {
    static var firstKeyboard: CustomKeyboard {
        CustomKeyboardBuilder { proxy, onSubmit, feedback in
            KeyboardView(textProxy: proxy, onSubmit: onSubmit, systemFeedbackHandler: feedback)
        }
    }
}

struct KeyboardView: View {
    let textProxy: UITextDocumentProxy?
    let onSubmit: CustomKeyboard.SubmitHandler?
    let systemFeedbackHandler: CustomKeyboard.SystemFeedbackHandler?
    
    init(textProxy: UITextDocumentProxy? = nil, onSubmit: CustomKeyboard.SubmitHandler? = nil, systemFeedbackHandler: CustomKeyboard.SystemFeedbackHandler? = nil) {
        self.textProxy = textProxy
        self.onSubmit = onSubmit
        self.systemFeedbackHandler = systemFeedbackHandler
    }
    
    init() {
        self.textProxy = nil
        self.onSubmit = nil
        self.systemFeedbackHandler = nil
    }
    
    var body: some View {
        GeometryReader { geometry in
            HStack {
                ZStack {
                    Rectangle()
                    VStack {
                        Button("Hello World") { }
                        Button("Hello World") { }
                        Button("Hello World") { }
                    }
                }
                .frame(maxWidth: geometry.size.width * 0.75)
                .background(.blue)
                
                ZStack {
                    Rectangle()
                    VStack {
                        Button("Hello World") { }
                        Button("Hello World") { }
                        Button("Hello World") { }
                    }
                }
                .frame(maxWidth: geometry.size.width * 0.25)
                .background(.red)
            }
        }
    }
}

#Preview {
    KeyboardView()
}
`

**Comment by paescebu** [comment]
Hi @l3rosiah 

You were close. The thing with the GeometryReader is: 
The GeometryReader takes the space of what the parent provides. It expands as much as it can, and the subviews of it are then limited to be laid out based on that available space. now the CustomKeyboard will not provide space (the short height) by nature. What you can do is enforce a set height by giving the GeometryReader a frame as it's parent. That forces the CustomKeyboard to follow that layout requirement and the GeometryReader then takes the whole space you set.
It's as simple as adding a frame modifier outside the GeometryReader :) See below: 

```swift
extension CustomKeyboard {
    static var firstKeyboard: CustomKeyboard {
        CustomKeyboardBuilder { proxy, onSubmit, feedback in
            KeyboardView(textProxy: proxy, onSubmit: onSubmit, systemFeedbackHandler: feedback)
        }
    }
}

struct KeyboardView: View {
    let textProxy: UITextDocumentProxy?
    let onSubmit: CustomKeyboard.SubmitHandler?
    let systemFeedbackHandler: CustomKeyboard.SystemFeedbackHandler?
    
    init(textProxy: UITextDocumentProxy? = nil, onSubmit: CustomKeyboard.SubmitHandler? = nil, systemFeedbackHandler: CustomKeyboard.SystemFeedbackHandler? = nil) {
        self.textProxy = textProxy
        self.onSubmit = onSubmit
        self.systemFeedbackHandler = systemFeedbackHandler
    }
    
    init() {
        self.textProxy = nil
        self.onSubmit = nil
        self.systemFeedbackHandler = nil
    }
    
    var body: some View {
        GeometryReader { geometry in
            HStack {
                ZStack {
                    Rectangle()
                    VStack {
                        Button("Hello World") { }
                        Button("Hello World") { }
                        Button("Hello World") { }
                    }
                }
                .frame(maxWidth: geometry.size.width * 0.75)
                .background(.blue)
                
                ZStack {
                    Rectangle()
                    VStack {
                        Button("Hello World") { }
                        Button("Hello World") { }
                        Button("Hello World") { }
                    }
                }
                .frame(maxWidth: geometry.size.width * 0.25)
                .background(.red)
            }
        }
        .frame(height: 250)
    }
}

#Preview {
    KeyboardView()
}

```

I hope that helps.

Kind regards and a great weekend!
Pascal

**Comment by l3rosiah** [comment]
Ahh ok got it. I had tried embedding it in some parent views but they were also auto-adjusting and therefore weren't accomplishing anything. Thank you again or the quick responses and help!

**Comment by paescebu** [comment]
Hi @l3rosiah No issues!
Yeah simple parent views without any modifiers that restrict the frames in some way simply inherit the behaviour that is defined by their parent or child (by design). 

Glad I could help!

Happy coding and a great week!

Kind regards
Pascal
