### ISSUE TITLE
Unable to pass conditionals or state variables in/out of the custom keyboard

### ISSUE THREAD

**Issue by l3rosiah** [paescebu/CustomKeyboardKit#14]
I am attempting to implement something a "Shift" key so that I can shift over to so alternate characters being shown by clicking it. However, anytime I try and use a state variable from within the custom keyboard it fails completely. I tested my code in a simple view and it worked fine, but not within the custom keyboard modifier.

`struct KeyboardView: View {
    
    @State private var isShiftHeld = false
    
    let fullTexts = ["SHIFT", "A", "B", "C", "D", "E", "", "7", "8", "9", "F", "G", "H", "I", "J", "K", "", "4", "5", "6", "L", "M", "N", "O", "P", "Q", "", "1", "2", "3", "R", "S", "T", "U", "V", "W", "", "-", "0", ".", "X", "Y", "Z", ":", "(", ")", "", "CANCEL", "SPACE", "ENTER"]
    let fullAltTexts = ["SHIFT", "A", "B", "C", "D", "E", "", "&", "@", ":", "F", "G", "H", "I", "J", "K", "", "%", "$", "!", "L", "M", "N", "O", "P", "Q", "", "*", ",", "?", "R", "S", "T", "U", "V", "W", "", "+", "=", "#", "X", "Y", "Z", ":", "[", "]", "", "CANCEL", "SPACE", "ENTER"]

    let fullGrid = Array(repeating: GridItem(), count: 10)
    
    var body: some View {
        Text(isShiftHeld ? "true" : "false")
        LazyVGrid(columns: fullGrid) {
            ForEach(fullTexts.indices, id: \.self) { index in
                Button(action: {
                    if index == 0 {
                        isShiftHeld.toggle()
                    }
                }) {
                    Text(isShiftHeld ? fullAltTexts[index] : fullTexts[index])
                        .frame(width: 60, height: 60)
                        .foregroundColor(.white)
                        .background(.blue)
                        .cornerRadius(8)
                }
                .padding()
            }
        }
        .padding()
    }
}

#Preview {
    KeyboardView()
}`

**Comment by paescebu** [comment]
Hi @l3rosiah.
I tried your code and it seems to work fine on my machine (iOS17.0 Simulator). Heres my full example

```swift

struct ContentView: View {
    @State private var value: String = "Test"
    
    var body: some View {
        TextField("", text: $value)
            .customKeyboard(.firstKeyboard)
    }
}

extension CustomKeyboard {
    static var firstKeyboard: CustomKeyboard {
        CustomKeyboardBuilder { proxy, onSubmit, feedback in
            KeyboardView(textProxy: proxy, onSubmit: onSubmit, systemFeedbackHandler: feedback)
        }
    }
}

struct KeyboardView: View {
    @State private var isShiftHeld = false
    let textProxy: UITextDocumentProxy?
    let onSubmit: CustomKeyboard.SubmitHandler?
    let systemFeedbackHandler: CustomKeyboard.SystemFeedbackHandler?

    let fullTexts = ["SHIFT", "A", "B", "C", "D", "E", "", "7", "8", "9", "F", "G", "H", "I", "J", "K", "", "4", "5", "6", "L", "M", "N", "O", "P", "Q", "", "1", "2", "3", "R", "S", "T", "U", "V", "W", "", "-", "0", ".", "X", "Y", "Z", ":", "(", ")", "", "CANCEL", "SPACE", "ENTER"]
    let fullAltTexts = ["SHIFT", "A", "B", "C", "D", "E", "", "&", "@", ":", "F", "G", "H", "I", "J", "K", "", "%", "$", "!", "L", "M", "N", "O", "P", "Q", "", "*", ",", "?", "R", "S", "T", "U", "V", "W", "", "+", "=", "#", "X", "Y", "Z", ":", "[", "]", "", "CANCEL", "SPACE", "ENTER"]
    
    let fullGrid = Array(repeating: GridItem(), count: 10)
    
    init(textProxy: UITextDocumentProxy? = nil, onSubmit: CustomKeyboard.SubmitHandler? = nil, systemFeedbackHandler: CustomKeyboard.SystemFeedbackHandler? = nil) {
        self.textProxy = textProxy
        self.onSubmit = onSubmit
        self.systemFeedbackHandler = systemFeedbackHandler
    }
    
    init() {
        self.textProxy = nil
        self.onSubmit = nil
        self.systemFeedbackHandler = nil
    }
    
    var body: some View {
        Text(isShiftHeld ? "true" : "false")
        LazyVGrid(columns: fullGrid) {
            ForEach(fullTexts.indices, id: \.self) { index in
                Button(action: {
                    if index == 0 {
                        isShiftHeld.toggle()
                    } else if fullTexts[index] == "ENTER" {
                        onSubmit?()
                    } else {
                        textProxy?.insertText(isShiftHeld ? fullAltTexts[index] : fullTexts[index])
                    }
                    systemFeedbackHandler?()
                }) {
                    Text(isShiftHeld ? fullAltTexts[index] : fullTexts[index])
                        .frame(width: 60, height: 60)
                        .foregroundColor(.white)
                        .background(.blue)
                        .cornerRadius(8)
                }
                .padding()
            }
        }
        .padding()
    }
}

#Preview {
    KeyboardView()
}
```
See video:
https://github.com/paescebu/CustomKeyboardKit/assets/59558722/106eeff2-e26c-4687-aa01-88693665156c

**Comment by l3rosiah** [comment]
Wow thank you so much for that example! That's super helpful and working exactly how I want! I was trying to set it all up within the .customKeyboard {} closure similar to the README example which is where my issues were stemming from. This is much more clear and clean. As I mentioned in my other comment I'm still learning so I appreciate all the help I can get! I'll go ahead and close the issue- thank you again for the help and for putting together this awesome project! It makes it so easy!

**Comment by paescebu** [comment]
Very happy to help :) 
No issues, experience comes with practice. But what you faced initially is a limitation of my library that I haven't come around yet to find a solution for. Theoretically your expectation was correct and what you wanted to work, should have worked. Definitely not your fault.
