### ISSUE TITLE
[Question] playing different feedback sounds i.e input and delete

### ISSUE THREAD

**Issue by xzilja** [paescebu/CustomKeyboardKit#18]
Hi 👋 

Not sure if issues is correct place to ask this, as it is more of a question, but is it possible to somehow define which feedback sound needs to be played? As of now, it seems like "Input" sound is the only available option, but playing around with ios default keyboard there are 3 distinctive sounds for

1. Clicking on letters
2. Clicking on space / shift / done
3. Clicking on delete / backspace

Would it be possible to add an argument to `playSystemFeedback` function that allows to define which sound should be played for custom keyboards?

**Comment by paescebu** [comment]
@xzilja Thanks for the suggestion!

I thought about this a lot. Theoretically theres APIs on Apple's side to select which sound ID can be played. But I don't want to switch to that yet, cause it feels a bit hacky to rely on. 
Also `UIDevice.current.playInputClick()` (which CustomKeyboardKit currently uses under the hood) handles automagically if the user has enabled/disabled keyboard input sounds and haptic feedback in the system settings. Whereas any other way I would lose the convenience. Or at least those are the limitations that i am currently aware of.

But theoretically you can _just_ not use the SystemFeedback Handler and instead play your custom preferred sounds upon button clicks. And use something along those lines inside:

```swift
enum NativeSystemSound: UInt32 {

    case click    = 1123
    case delete   = 1155
    case modifier = 1156

    func play() {
        AudioServicesPlaySystemSound(self.rawValue)
    }
}
```
