### ISSUE TITLE
Only calls one 'onSubmitCustomKeyboard'

### ISSUE THREAD

**Issue by SPMen** [paescebu/CustomKeyboardKit#2]
This is such a help....thank you so much for posting it. You're absolutely right to say it is the easiest way to add a custom keyboard to SwiftUI. 

I've been having one issue: only one `onSubmitCustomKeyboard` is called, even if I have multiple instances with a few different text fields. I thought at first it might be something in my code, so here's what I did to check: I started a new project in Xcode, installed the package, and copied the code of your sample `yesnt` keyboard. Then I only slightly modified your sample implementation:

```
struct ContentView: View {

    @State var text1: String = ""
    @State var text2: String = ""
    @State var text3: String = ""

        var body: some View {
            VStack {
                Text("Textfield #1:")
                TextField("", text: $text1)
                    .customKeyboard(.yesnt)
                    .onSubmitCustomKeyboard {
                        print("Textfield #1 submit")
                    }
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("Textfield #2")
                TextField("", text: $text2)
                    .customKeyboard(.yesnt)
                    .onSubmitCustomKeyboard {
                        print("Textfield #2 submit")
                    }
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("Textfield #3")
                TextField("", text: $text3)
                    .customKeyboard(.yesnt)
                    .onSubmitCustomKeyboard {
                        print("Textfield #3 submit")
                    }
                    .textFieldStyle(RoundedBorderTextFieldStyle())
            }
        }
    }

```

When run, only the first `onSubmitCustomKeyboard` is ever called ("Textfield #1 submit"), even when `submit?()` is called in Textfield #2 or Textfield #3. 

Is that how it is supposed to work? In my own actual project, for some reason it is oddly calling the third instance of `onSubmitCustomKeyboard` every time, and I can't make sense of why.

**Comment by paescebu** [comment]
Hey! Thanks for your kind words!Very good find! I'll take a look at it as soon as possible!
I agree that it should not work like this!

**Comment by paescebu** [comment]
Hey @SPMen,
Good news, I think i managed to find a solution that keeps the API the same, just how the CustomKeyboard needs to be declared changes slightly (a static computed property instead of a static stored property), see the examples in the adjusted README :) 
Can you try out the implementation of the linked branch and tell me if it fixes the issue for you? 

Kind regards
Pascal

**Comment by SPMen** [comment]
Hello Pascal,

Wow...yes, this works great!!! I tried the changes on the test code I posted and on my own project. It worked perfectly for both. 

Thank you for sharing CustomKeyboardKit...it really is so helpful, so simple, and a gift to those of us who use it (and aren't quite as impressive in programming as you are). You are kind to share!

Take care,
Stephen

**Comment by paescebu** [comment]
Omg thank you for your kind words!

I will merge it to master directly so that youll have the changes when you directly fetch the Swift Package next time :-)

Have a great weekend!
Pascal

**Comment by bwalton** [comment]
@paescebu anywhere I can buy you a coffee or show some support?

**Comment by paescebu** [comment]
> @paescebu anywhere I can buy you a coffee or show some support?

@bwalton haha it's really not necessary to pay me anything. 
But i quickly and dirty set up a PayPal donation link. It's in the updated README.

Thanks for appreciating my tiny package anyway!
