### ISSUE TITLE
Question: Can this be used when creating a custom keyboard extension?

### ISSUE THREAD

**Issue by puhgeh** [paescebu/CustomKeyboardKit#21]
Is it possible to incorporate this in a custom keyboard extension? 

If so, would you be able to provide an example on how to use it inside the `KeyboardViewController: UIInputViewController`?

Thanks!

**Comment by paescebu** [comment]
@puhgeh let me look into this further. If you want to use SwiftUI in your KeyboardViewController class, you can simply just add a SubView which embeds the `UIHostingViewController` with the SwiftUI View of you choice. This library is not needed for that, especially as it has to fullfill some other requirements to work well with other Keyboards from iOS (e.g. Keyboard switching etc.). 

But to simply embed a SwiftUI View into your `KeyboardViewController` you should be able to do something along those lines (code not checked if it compiles):

```swift
public class KeyboardViewController: UIInputViewController {
    lazy var keyboardView = UIHostingController(rootView: yourSwiftUIKeyboard)
   
    public init() {
        super.init(nibName: nil, bundle: nil)
        addChild(keyboardView)
        view.addSubview(keyboardView.view)
        setupContraints()
    }

    @ViewBuilder
    var yourSwiftUIKeyboard: some View {
         Button("A") {
               self.textDocumentProxy.insertText("A")
         }
         Button("B") {
               self.textDocumentProxy.insertText("B")
         }
    }

    private func setupContraints() {
        contentView.view.translatesAutoresizingMaskIntoConstraints = false
        contentView.view.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        contentView.view.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        contentView.view.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
        contentView.view.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```
