### ISSUE TITLE
Keyboard + Top bar with buttons

### ISSUE THREAD

**Issue by Afondevi** [paescebu/CustomKeyboardKit#23]
Hello, I get an issue when creating a Topbar button.

First, I see my top bar button, then the keyboard appears after a delay, and masks my top bar, instead of having it at the top.

Thanks for your help.

**Comment by paescebu** [comment]
Hi @Afondevi!
Thx for the report!
Could you provide some example code to showcase the issue?

Happy to give it a try and see what I can do.

Regards
Pascal
