### ISSUE TITLE
Modifying state during view update

### ISSUE THREAD

**Issue by sveinhal** [paescebu/CustomKeyboardKit#4]
XCode 14.3 gives a runtime warning on mutation-during-update:

<img width="1365" alt="Skjermbilde 2023-05-09 kl  09 56 33" src="https://user-images.githubusercontent.com/88693/237044124-bdad3ee1-10ba-4140-8464-f350eedf61dd.png">

**Comment by paescebu** [comment]
Thx for the report!

I will dig into it

Regards!

**Comment by paescebu** [comment]
@sveinhal I don't manage to reproduce this issue in Xcode 14.3. 
Can you maybe provide me with a small example project? Or some detailed description on how you managed to get the error?

**Comment by paescebu** [comment]
Closed the issue as i can't reproduce it and no example was given to reproduce it.

Can be reopened if it can be reproduced
