### ISSUE TITLE
Missing important keys

### ISSUE THREAD

**Issue by shahriar-ax** [paescebu/CustomKeyboardKit#6]
in custom keyboard has no **delete** button, **case change** button & no **dismiss or done** button

**Comment by paescebu** [comment]
Hi @shahriar-ax,

That's correct. Everything that is text manipulation you have to implement yourself by manipulating the string using the 'UITextDocumentProxy'.

To give you an example for the logic for deleting the character left of the cursor:

'''swift
var deleteButton: some View {
        Button {
            textProxy.deleteBackward()
            }
        } label: {
            Text("DEL")
        }
}
'''

**Comment by paescebu** [comment]
Closed due to inactivity
