### ISSUE TITLE
SwiftUI-Introspect dependency outdate

### ISSUE THREAD

**Issue by wenweih** [paescebu/CustomKeyboardKit#7]
The library  doesn't work for latest version of `SwiftUI-Introspect` (0.10.0)

**Comment by paescebu** [comment]
Hi @wenweih!
It uses an exact version dependency 0.7.0 currently. 
Can you elaborate what exactly you mean by it not working? :)

**Comment by paescebu** [comment]
@wenweih, I updated the package to consume the latest SwiftUI-Introspect version.
Does that solve your issue?

**Comment by wenweih** [comment]
Hi @paescebu , thank you so much. it works.
